services:
  - type: web
    name: medical-generator
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
